In [7]:
import pandas as pd
import pyfixest as pf

In [8]:
data = pf.get_data()

In [9]:
fit = pf.feols("Y ~ X1", data)
fit.summary()

###

Estimation:  OLS
Dep. var.: Y, Fixed effects:
Inference:  iid
Observations:  998

| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |
|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|
| Intercept     |      0.919 |        0.112 |     8.214 |      0.000 |  0.699 |   1.138 |
| X1            |     -1.000 |        0.085 |   -11.802 |      0.000 | -1.166 |  -0.834 |
---
RMSE: 2.158 R2: 0.123

In [10]:
fit.tidy(alpha=0.5)

             Estimate  Std. Error    t value      Pr(>|t|)      2.5%     97.5%
Coefficient
Intercept    0.918518    0.111821   8.214166  6.661338e-16  0.843068  0.993968
X1          -1.000086    0.084735 -11.802468  0.000000e+00 -1.057260 -0.942912

In [11]:
fit.confint(alpha=0.05)

             0.025%    0.975%
Intercept  0.699086  1.137950
X1        -1.166366 -0.833806

In [12]:
fit.coefplot(alpha = 0.5)